---
title: "EEDS Power consumption"
author: "Bharathwaj Rajan; Marlon Cabrera Ormaza; Martin Freisehner; Tamas Birkner;"
date: "28 April 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download dataset

```{r }
library(ggplot2)
library(mice)
library(openair)
library(forecast)
library(tseries)
library(timeSeries)
library(TSA)
library(timeSeries)
library(Metrics)
theme_set(theme_bw())


energy.ds.url <- "http://combed.github.io/downloads/combed.zip"
energy.folder <- "res/energy"
energy.ds.zip.path <- file.path(energy.folder, "combed.zip")
energy.ds.path <- file.path(energy.folder, "iiitd/Academic Block/Building Total Mains/0/Power.csv")

# download file if no present
if (!file.exists(energy.ds.zip.path)) {
  print("Downloading combed dataset...")
  dir.create(energy.folder, recursive = TRUE, showWarnings = FALSE)
  download.file(energy.ds.url, energy.ds.zip.path)
}

# unzip archive if not already done
if (!file.exists(energy.ds.path)) {
  unzip(energy.ds.path, exdir = energy.folder)
}

# read in data
energy.df <- read.csv(energy.ds.path,
                      header = FALSE,
                      col.names = c('timestamp', 'power'))

# convert unix timestamps to date types
energy.df$timestamp <- as.POSIXct(energy.df$timestamp/1000, origin = "1970-01-01")
head(energy.df)
```

## Exploratory analysis

```{r }
summary(energy.df)
```

```{r }
library(ggplot2)
theme_set(theme_bw())

ggplot(data = energy.df, aes(x = timestamp, y = power)) +
  geom_line(color = "#00AFBB", size = .5) +
  stat_smooth(color = "#FC4E07", fill = "#FC4E07") +
  ggtitle("Power consumption over 1 month") +
  labs(x = "Date", y = "Power [kW]")
```

```{r }
energy.df.1w <- subset(energy.df, timestamp > as.POSIXct('2014-06-02 12:00:00') & timestamp < as.POSIXct('2014-06-09 12:00:00'))
ggplot(data = energy.df.1w, aes(x = timestamp, y = power)) +
  geom_line(color = "#00AFBB", size = .5) +
  scale_x_datetime(date_labels = "%a", date_breaks = "1 day") +
  stat_smooth(color = "#FC4E07", fill = "#FC4E07") +
  ggtitle("Power consumption over 1 week") +
  labs(x = "Date", y = "Power [kW]")
```


```{r }
energy.df.1d <- subset(energy.df, timestamp > as.POSIXct('2014-06-04 00:00:00') & timestamp < as.POSIXct('2014-06-05 00:00:00'))
ggplot(data = energy.df.1d, aes(x = timestamp, y = power)) +
  geom_line(color = "#00AFBB", size = .5) +
  scale_x_datetime(date_labels = "%H:%M", date_breaks = "2 hours") +
  stat_smooth(color = "#FC4E07", fill = "#FC4E07") +
  ggtitle("Power consumption over 1 day") +
  labs(x = "Date", y = "Power [kW]")
```

```{r}
#Creating gaps in data
stddev<-sd(energy.df$power)
med<-mean(energy.df$power)





#gap=2 #Choose this for gap of a minute
#gap=120 #choose for gap o 1 hour
#gap=30 #choose for 30 minute gap
gap=2874 #choose for day gap

L=length(energy.df$power)
LL=floor(L-2874)
N<-L/gap
M<-floor(N*0.8)
P<-N-M

foo <- rnorm(n=LL, mean=med, sd=stddev)

ind <- which(foo %in% sample(foo, P))

energy<-energy.df


for (i in 1:gap){ energy$power[ind+i]<-NA}
for (j in 1:L){
  if(is.na(energy$power[j])||j>LL){
    energy$extracted[j]=energy.df$power[j]
  } else {
    energy$extracted[j]<-NA
  }
}

#Clean the time series

energy$power_clean<-tsclean(energy$power,lambda = "auto")


```


```{r}
p=periodogram(energy$power_clean)
dd = data.frame(freq=p$freq, spec=p$spec)
order = dd[order(-dd$spec),]
top2 = head(order, 2)
 
# display the 2 highest "power" frequencies
top2


# convert frequency to time periods
time = 1/top2$f
time
```



```{r}
ts_energy<-ts(energy$power_clean,frequency = 2874)
stl_energy<-stl(ts_energy,"periodic")
seasonal_stl_energy   <- stl_energy$time.series[,1]
trend_stl_energy     <- stl_energy$time.series[,2]
random_stl_energy  <- stl_energy$time.series[,3]
plot(ts_energy)
plot(stl_energy)
```






```{r}


#Use auto.arima to fit model
fit_non_seasonal<-auto.arima(trend_stl_energy[-c(LL:L)],seasonal = FALSE)
fit_seasonal<-auto.arima(seasonal_stl_energy[-c(LL:L)],seasonal = TRUE)
fit_random<-auto.arima(random_stl_energy[-c(LL:L)],seasonal = FALSE)


fcast_non_seasonal<- forecast(fit_non_seasonal, h=(L-LL))
fcast_seasonal<- forecast(fit_seasonal, h=(L-LL))
fcast_random<- forecast(fit_random, h=(L-LL))


```

```{r}
#Forecasting series decomposition

plot(fcast_seasonal)
plot(fcast_non_seasonal)
plot(fcast_random)



new_energy<-fcast_non_seasonal$x+fcast_random$x+fcast_seasonal$x


new_forecast<-fcast_non_seasonal$mean+fcast_random$mean+fcast_seasonal$mean
plot(energy$power_clean)
points(energy$extracted[-c(LL:L)],col="red",pch = ".")
lines(new_forecast,col="blue")
error<-rmse(energy$power_clean[(LL+1):L],new_forecast)
error



```


