---
title: "EEDS Power consumption"
author: "Bharathwaj Rajan; Marlon Cabrera Ormaza; Martin Freisehner; Tamas Birkner;"
date: "28 April 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download dataset

```{r }
energy.ds.url <- "http://combed.github.io/downloads/combed.zip"
energy.folder <- "res/energy"
energy.ds.zip.path <- file.path(energy.folder, "combed.zip")
energy.ds.path <- file.path(energy.folder, "iiitd/Academic Block/Building Total Mains/0/Power.csv")

# download file if no present
if (!file.exists(energy.ds.zip.path)) {
  print("Downloading combed dataset...")
  dir.create(energy.folder, recursive = TRUE, showWarnings = FALSE)
  download.file(energy.ds.url, energy.ds.zip.path)
}

# unzip archive if not already done
if (!file.exists(energy.ds.path)) {
  unzip(energy.ds.path, exdir = energy.folder)
}

# read in data
energy.df <- read.csv(energy.ds.path,
                      header = FALSE,
                      col.names = c('timestamp', 'power'))

# convert unix timestamps to date types
energy.df$timestamp <- as.POSIXct(energy.df$timestamp/1000, origin = "1970-01-01")
head(energy.df)
```

## Exploratory analysis

```{r }
summary(energy.df)
```

```{r }
library(ggplot2)
theme_set(theme_bw())

ggplot(data = energy.df, aes(x = timestamp, y = power)) +
  geom_line(color = "#00AFBB", size = .5) +
  stat_smooth(color = "#FC4E07", fill = "#FC4E07") +
  ggtitle("Power consumption over 1 month") +
  labs(x = "Date", y = "Power [kW]")
```

```{r }
energy.df.1w <- subset(energy.df, timestamp > as.POSIXct('2014-06-02 12:00:00') & timestamp < as.POSIXct('2014-06-09 12:00:00'))
ggplot(data = energy.df.1w, aes(x = timestamp, y = power)) +
  geom_line(color = "#00AFBB", size = .5) +
  scale_x_datetime(date_labels = "%a", date_breaks = "1 day") +
  stat_smooth(color = "#FC4E07", fill = "#FC4E07") +
  ggtitle("Power consumption over 1 week") +
  labs(x = "Date", y = "Power [kW]")
```


```{r }
energy.df.1d <- subset(energy.df, timestamp > as.POSIXct('2014-06-04 00:00:00') & timestamp < as.POSIXct('2014-06-05 00:00:00'))
ggplot(data = energy.df.1d, aes(x = timestamp, y = power)) +
  geom_line(color = "#00AFBB", size = .5) +
  scale_x_datetime(date_labels = "%H:%M", date_breaks = "2 hours") +
  stat_smooth(color = "#FC4E07", fill = "#FC4E07") +
  ggtitle("Power consumption over 1 day") +
  labs(x = "Date", y = "Power [kW]")
```